const emails = [
    {
        id: 1,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 2,
        sender: "SimpliLearn",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "04 May",
        read: false,
    },
    {
        id: 3,
        sender: "SimpliLearn",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "04 May",
        read: false,
    },
    {
        id: 4,
        sender: "SimpliLearn",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "04 May",
        read: false,
    },
    {
        id: 5,
        sender: "SimpliLearn",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "04 May",
        read: false,
    },
    {
        id: 6,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "25 Apr",
        read: false,
    },
    {
        id: 7,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 8,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 9,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 10,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 11,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 12,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 13,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
    {
        id: 14,
        sender: "Medium Daily Digest",
        subject: "How to classify your design system-a framework | Joy Speaks at UX Collective",
        date: "24 May",
        read: false,
    },
];

export default emails;